from coffee.schemas.base_schema import with_base_properties


@with_base_properties
def get_series_schema():
    return {
        '$schema': 'http://json-schema.org/draft-04/schema#',
        'id': 'string',
        'properties': {
            'name': {'type': 'string'},
            'description': {'type': ['string', 'null']},
            'alias': {'type': ['string', 'null']},
            'is_calculation': {'type': 'boolean', 'default': False},
            'aggregation': {'type': 'string', 'default': 'total'},
            'engineering_unit_id': {'type': ['string', 'null']},
            'fill_method': {'type': ['string', 'null']},
            'post_processor': {'type': ['string', 'null']},
            'accumulation': {'type': ['boolean', 'null']},
            'allow_edit': {'type': ['boolean', 'null']},
            'delete_hihilowlow': {'type': ['boolean', 'null']},
            'sample_period': {'type': ['string', 'null']},
            'sample_offset': {'type': ['integer', 'null']},
            'assumptions': {'type': ['string', 'null']},
            'weighted_average_id': {'type': ['string', 'null']},
            'event_type_id': {'type': ['string', 'null']},
            'hi': {'type': ['number', 'null']},
            'hihi': {'type': ['number', 'null']},
            'low': {'type': ['number', 'null']},
            'lowlow': {'type': ['number', 'null']},
            'mean': {'type': ['number', 'null']},
            'std': {'type': ['number', 'null']},
            'default_value': {'type': ['number', 'null']},
            'rolling_average_hours': {'type': ['integer', 'null']},
            'kpi_level': {'type': ['string', 'null']},
            'default_chart': {'type': ['string', 'null']},  # TODO add enum
            'decimal_places': {'type': ['integer', 'null']},
            'formula': {'type': ['string', 'null']},
            'name_formula': {'type': ['string', 'null']},
            'specialised_function': {'type': ['boolean','null'], 'default': False},
            'allow_future_data': {'type': ['boolean','null'], 'default': False},
            'series_type': {'relation': 'to-one', 'resource': 'series_type'},
            'series_components': {'relation': 'to-many', 'resource': ['series_component']},
            'event_type': {'relation': 'to-one', 'resource': 'event_type'},
            'engineering_unit': {'relation': 'to-one', 'resource': 'engineering_unit'},
            'weighted_average_series': {'relation': 'to-one', 'resource': 'series'},
            'mappers': {'relation': 'to-many', 'resource': ['mapper']},
            'processes': {'relation': 'to-many', 'resource': ['process']},
            'series_users': {'relation': 'to-many', 'resource': ['users']},
            'target_series': {'relation': 'to-many', 'resource': ['series']},
            'source_series': {'relation': 'to-many', 'resource': ['series']},
            'component_constant_collation_series_export': {'relation': 'to-one',
                                                           'resource': 'component_constant_collation_series_export'},
            'event_constant_collation_series_export': {'relation': 'to-one',
                                                       'resource': 'event_constant_collation_series_export'},
            'extra_arguments_string': {'type': ['string', "null"]},
            'json': {'type': ['object', "null"]},
        },
        'type': 'object'
    }
